<?php

namespace CoreBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository {

    public function getCategoriesWithProducts() {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('c')
                ->from('CoreBundle:Category', 'c')
                ->leftJoin('c.products', 'p')
                ->addSelect('p');

        return $qb->getQuery()->getResult();
    }

    public function getCategoriesWithSubCategories() {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('c')
                ->from('CoreBundle:Category', 'c')
                ->leftJoin('c.categoriesChildren', 'sc')
                ->addSelect('sc')
                ->where($qb->expr()->isNull('c.categoryParent'));

        return $qb->getQuery()->getResult();
    }

    public function getOnlyParentsCategories() {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('c')
                ->from('CoreBundle:Category', 'c')
                ->where($qb->expr()->isNull('c.categoryParent'));

        return $qb->getQuery()->getResult();
    }

}
